[versions]
assertj = "3.23.1"
groovy = "4.0.3"
gson = "2.9.0"
junit = "5.9.0-M1"
kotlin = "1.7.0"
kotlin-coroutines = "1.6.3"
kotlin-serialization = "1.3.3"
kotlin-serialization-converter = "0.8.0"
spock = "2.2-M1-groovy-4.0"
retrofit = "2.9.0"

[libraries]
assertj = { module = "org.assertj:assertj-core", version.ref = "assertj" }
groovy = { module = "org.apache.groovy:groovy", version.ref = "groovy" }
groovy-json = { module = "org.apache.groovy:groovy-json", version.ref = "groovy" }
groovy-swing = { module = "org.apache.groovy:groovy-swing", version.ref = "groovy" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
kotlin-script-runtime = { module = "org.jetbrains.kotlin:kotlin-script-runtime", version.ref = "kotlin" }
kotlin-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlin.coroutines" }
kotlin-serialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlin.serialization" }
kotlin-converter = { module = "com.jakewharton.retrofit:retrofit2-kotlinx-serialization-converter", version.ref = "kotlin.serialization.converter" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }
junit-vintage = { module = "org.junit.vintage:junit-vintage-engine", version.ref = "junit" }
retrofit-core = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
spock = { module = "org.spockframework:spock-core", version.ref = "spock" }

[bundles]
junit = ["junit-jupiter", "junit-vintage"]

[plugins]
versions = { id = "com.github.ben-manes.versions", version = "0.42.0" }
version-catalog-update = { id = "nl.littlerobots.version-catalog-update", version = "0.5.1" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin"  }
